config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'users#index'

  get 'users/search' => 'users#search'
  get 'comments/index' => 'comments#index'

  resources :users, only: [:show] do
  end
  resources :comments, only: [:create] do
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :from, class_name: "User"
  belongs_to :to, class_name: "User"

    # Scopes
  default_scope -> {order(created_at: :asc)}

  # Validations
  validates :from_id, presence: true
  validates :to_id, presence: true
  validates :room_id, presence: true
  validates :text, presence: true, length: {maximum: 50}

  # Methods
  def Comment.recent_in_room(room_id)
    where(room_id: room_id).last(500)
  end

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :comments

  has_many :from_comments, class_name: "Comment",
          foreign_key: "from_id", dependent: :destroy
  has_many :to_comments, class_name: "Comment",
            foreign_key: "to_id", dependent: :destroy
  has_many :sent_comments, through: :from_comments, source: :from
  has_many :received_comments, through: :to_comments, source: :to

  validates :nickname, presence: true
  validates :address, presence: true
  validates :postcode, presence: true

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:nickname, :address, :postcode])
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  def index
    @allcomments = Comment.where(to_id: current_user).or(Comment.where(from_id: current_user))
  end

  def create
    Comment.create!(comment_params)
    redirect_to :back
  end

  private
  def comment_params
    params.permit(:text, :from_id, :to_id, :room_id,:user_id)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!, except: :index

  def index
  end

  def show
    @user = User.find(params[:id])
    @room_id = comment_room_id(current_user, @user)
    @comments = Comment.recent_in_room(@room_id)
  end

  def comment_room_id(first_user, second_user)
  first_id = first_user.id.to_i
  second_id = second_user.id.to_i
    if first_id < second_id
      "#{first_user.id}-#{second_user.id}"
    else
      "#{second_user.id}-#{first_user.id}"
    end
  end

  def search
    @users = User.where('postcode LIKE(?)', "%#{params[:search]}%").where.not(id: current_user)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/comments/_comment_form.html.haml
= form_tag('/comments', method: :post) do
  %textarea.comment-box{:cols => "40", :name => "text",:placeholder => "メッセージを入力",:rows => "4"}
  %input{:name => "user_id", :type => "hidden", :value => from_user.id}/
  %input{:name => "from_id", :type => "hidden", :value => from_user.id}/
  %input{:name => "to_id", :type => "hidden", :value => @user.id}/
  %input{:name => "room_id", :type => "hidden", :value => @room_id}/
  %button{class: "user-mypage-container__submit",:type => "submit"}
    #{to_user.nickname} さんへ送信

app/views/comments/index.html.haml
.user-mypage-container
  %div.user-mypage-container__inner
    %div.comment-container
      %h1.comment-container__title <メッセージ一覧>
      %div.mypage-comment-container
        - if @allcomments
          - @allcomments.each do |comment|
            - if comment.from_id != current_user.id
              %div.receive-comment
                %p
                = link_to user_path(comment.from_id) do
                  = comment.user.nickname
                ：
                = comment.text
                %br
                = comment.created_at.strftime("%Y/%m/%d %H:%M")
              %br
            - else
              %div.comment-right
                %div.send-comment
                  %p
                  = comment.user.nickname
                  ：
                  = comment.text
                  %br
                  = comment.created_at.strftime("%Y/%m/%d %H:%M")
                %br

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %meta{:content => "width=device-width, initial-scale=1.0", :name => "viewport"}/
    %title OriginalApp
    = csrf_meta_tags
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
    %link{:href => "https://use.fontawesome.com/releases/v5.6.1/css/all.css", :rel => "stylesheet"}/
  %body
    = yield

app/views/shared/_header.html.haml
%header.main-header
  %div.main-header__inner
    = link_to root_path, class: "main-header__title" do
      %h2 Receiver
    - if user_signed_in?
      %span.fa.fa-bars.menu-icon
      %ul.menu-list
        %li.menu-list__box
          = link_to comments_index_path, class: "menu-list__text" do
            メッセージ確認
        %li.menu-list__box
          = link_to destroy_user_session_path, method: :delete,class: "menu-list__text" do
            ログアウト
    - else
      %span.fa.fa-bars.menu-icon
      %ul.menu-list
        %li.menu-list__box
          = link_to new_user_session_path, class: "menu-list__text" do
            ログイン
        %li.menu-list__box
          = link_to new_user_registration_path, class: "menu-list__text" do
            新規会員登録
    %div.main-header__function
      %ul.login-register
      - if user_signed_in?
        %li
          = link_to comments_index_path, class: "header-mypage" do
            MESSAGES
            %br メッセージ
        %li
          = link_to destroy_user_session_path, method: :delete,class: "header-logout" do
            SIGN-OUT
            %br ログアウト
        %p ようこそ #{current_user.nickname} さん
      - else
        %li
          = link_to new_user_session_path, class: "header-login" do
            SIGN-IN
            %br ログイン
        %li
          = link_to new_user_registration_path, class: "header-signup" do
            SIGN-UP
            %br 新規会員登録

app/views/users/index.html.haml
%section.main-container
  = render 'shared/header'
  %h1.main-text 欲しい時に、受け取ろう
  %div.scroll-down
    %p.scroll-down__title SCROLL
    %i.fas.fa-angle-double-down

- if user_signed_in?
  %section.middle-container.scroll
    %div.middle-container__textbox
      %h3 近くのReceiverを探す
    = form_tag(users_search_path, method: :get,class: "middle-container__searchbox") do
      = text_field_tag :search, '', class: 'middle-container__input', placeholder: ' 郵便番号を入力'
      %button{class: "middle-container__searchbtn",:type => "submit"}
        %i.fas.fa-search
- else
  %section.middle-container.scroll
    = link_to new_user_registration_path, class: "middle-container__textbox" do
      %div.middle-container__textbox
        %h3 近くのReceiverを探す

%section.description.scroll
  %div.description-container
    %div.description-container__imagebox
    %div.description-container__textbox
      %h1.description-container__textbox--title Receiverとは？
      %br
      %p 最近はインターネットが普及し、欲しいものがすぐに注文できる時代です。
      %p しかし、荷物の多くは土日に配達依頼が集中し、時間通りに届かなかったり、再配達になってしまうことがあります。
      %p 「誰か自分の代わりに受け取ってくれる人がいたらなぁ・・・」
      %p そんな想いを実現できるのが、このReceiverです。
      %p まずは自分の家の近くで登録されているReceiverを探します。
      %p あとは登録されれている人と、受け取り日時などのやり取りをして荷物を受け取って完了です。
      %div.view-more view more >>

%section.sub-description
  %div.sub-description__title
    %h1 使い方は「ユーザー登録」から簡単3step!
  %div.sub-description__illust-container
    %div.sub-description__stepbox
      %div.sub-description__stepbox--title step1
      %div.illustbox1
      %p ・近くのユーザーを検索し、メッセージを送信
    %div.sub-description__stepbox
      %div.sub-description__stepbox--title step2
      %div.illustbox2
      %p ・ユーザーは予定に合わせて返答
      %br
    %div.sub-description__stepbox
      %div.sub-description__stepbox--title step3
      %div.illustbox3
      %p ・荷物を受け取り
      %br

%footer.main-footer
  %div.main-footer__inner
    %div.main-footer__inner--textbox
      %p 作成者 HOSOKAWA DAIKI
      %p mail : test@gmail.com
      %p TEL : 080-0000-0000
    %div.main-footer__inner--copyright
      %small © 2019 Receiver

app/views/users/search.html.haml
.search-result-container
  %div.search-result-container__inner
    %h1.search-result-container__title 検索結果#{@users.length}件
    %div.search-result-container__users
      - @users.each do |user|
        %div.search-result__user-box
          %h3.search-result__user-name
            = user.nickname
          %h3.search-result__user-address
            = user.address
          %div.search-result__request
            = link_to user_path(user), class: "search-result__request" do
              %div 依頼する

app/views/users/show.html.haml
.user-mypage-container
  %div.user-mypage-container__inner
    %h1.user-mypage-container__title
    = render 'comments/comment_form', {from_user: current_user, to_user: @user, room_id: @room_id}
    %div.comment-container
      %h1.comment-container__title <メッセージ一覧>
      %div.comment-container__comments
        - if @comments
          - @comments.each do |comment|
            - if comment.from_id != current_user.id
              %div.receive-comment
                %p
                = comment.user.nickname
                ：
                = comment.text
                %br
                = comment.created_at.strftime("%Y/%m/%d %H:%M")
              %br
            - else
              %div.comment-right
                %div.send-comment
                  %p
                  = comment.user.nickname
                  ：
                  = comment.text
                  %br
                  = comment.created_at.strftime("%Y/%m/%d %H:%M")
                %br